# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    # Ejecuta el backend
    - name: Setup Node.js ${{ matrix.node-version }} for Backend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Backend Dependencies
      run: |
        cd express_backend
        npm install
    - name: Run Backend
      run: |
        cd express_backend
        npm run dev

    # Ejecuta el frontend
    - name: Setup Node.js ${{ matrix.node-version }} for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Frontend Dependencies
      run: |
        cd vite_frontend
        npm install
    - name: Run Frontend
      run: |
        cd vite_frontend
        npm run dev
